# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='books_wrote',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='journal_wrote',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
