# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170605_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsignup',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
