# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170608_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='/publisher/image/')),
                ('cmpny_name', models.CharField(max_length=200, null=True)),
                ('cmpny_website', models.CharField(max_length=2000, null=True)),
                ('cmpny_address', models.TextField(max_length=2000, null=True)),
                ('experience', models.TextField(max_length=2000, null=True)),
                ('phoneno', models.CharField(max_length=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PubSignup', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='/user/image/'),
        ),
    ]
