# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/publisher/image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/user/image/'),
        ),
    ]
