# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20170624_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='/user/image/'),
        ),
    ]
