# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20170624_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='publisher/images/'),
        ),
    ]
