# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20170624_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherprofile',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
