# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_publisherprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('mtitle', models.CharField(max_length=2000, null=True)),
                ('mabstract', models.CharField(max_length=2000, null=True)),
                ('photo', models.FileField(blank=True, upload_to='upload/')),
            ],
        ),
        migrations.RenameField(
            model_name='publisherprofile',
            old_name='experience',
            new_name='aboutcmpny',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.PublisherProfile'),
        ),
    ]
