# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20170630_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='mabstract',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='mtitle',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
