# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20170630_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
